### ISSUE TITLE
Error in opening zip file

### ISSUE THREAD

**Issue by zihuangning** [spotify/hdfs2cass#31]
when i follow the guide and run "hadoop jar $JAR $CLASS --input $INPUT --output $OUTPUT", i met the problem:
"
java.io.IOException: Error opening job jar: ./target/spotify-hdfs2cass-2.0-SNAPSHOT-jar-with-dependencies.jar
	at org.apache.hadoop.mapred.util.RunJar.main(RunJar.java:144)
	at org.apache.hadoop.mapred.JobShell.run(JobShell.java:55)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:79)
	at org.apache.hadoop.mapred.JobShell.main(JobShell.java:69)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:127)
	at java.util.jar.JarFile.<init>(JarFile.java:135)
	at java.util.jar.JarFile.<init>(JarFile.java:72)
	at org.apache.hadoop.mapred.util.RunJar.main(RunJar.java:142)
	... 4 more
"
i did nothing else.
what can i try to solve this problem?

**Comment by nresare** [comment]
If you are building hdfs2cass from the latest master in the git repository, the filename should be target/spotify-hdfs2cass-2.11-SNAPSHOT.jar as the version has been updated after the guide was written.

**Comment by zihuangning** [comment]
when i try: target/spotify-hdfs2cass-2.11-SNAPSHOT-jar-with-dependencies.jar
java.lang.RuntimeException: Cannot create job output directory /tmp/crunch-216940703
...
Caused by: org.apache.hadoop.fs.QuotaExceededException: org.apache.hadoop.fs.QuotaExceededException: The quota of /tmp is exceeded: namespace quota=500000 file count=500001, diskspace quota=549755813888000 diskspace=4877107376069
why it need so much place?

when i try :spotify-hdfs2cass-2.11-SNAPSHOT.jar
java.lang.NoClassDefFoundError: org/apache/crunch/Pipeline
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:270)
	at org.apache.hadoop.mapred.util.RunJar.main(RunJar.java:209)
	at org.apache.hadoop.mapred.JobShell.run(JobShell.java:55)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:79)
	at org.apache.hadoop.mapred.JobShell.main(JobShell.java:69)
Caused by: java.lang.ClassNotFoundException: org.apache.crunch.Pipeline
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
